Bump version 0.19
turing-usp/turingquant pull request #48
Opened 2021-04-10 03:40 UTC by lucas-leme

@anor4k  confima se eu fiz tudo certo plsss

2021-04-10 04:34 UTC, anor4k commented
docs tá 0.1.8 e setup 0.1.9
fora isso acho que tá tudo ok, aí é só fazer a tag e o release depois do merge

2021-04-10 04:35 UTC, anor4k requested changes

2021-04-10 04:35 UTC, anor4k commented on docs/conf.py
> +release = '0.1.8'
era pra ser 0.1.9 né

2021-04-10 13:18 UTC, lucas-leme commented on docs/conf.py
> +release = '0.1.8'
Atualizei pro 0.2.0 pq eu n tinha atualizado as docs do novo módulo. E eu já tinha dado tag 0.1.9 antes

2021-04-19 10:37 UTC, anor4k approved these changes

2021-05-03 20:31 UTC, merged